name: ❓ Question
description: Ask a question or get support
title: "[Question]: "
labels: ["question", "help wanted"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking a question! Please provide as much context as possible.
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. @username on Discord
    validations:
      required: false
      
  - type: textarea
    id: question
    attributes:
      label: What's your question?
      description: Please be as specific as possible about what you're trying to accomplish.
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What have you tried so far? What documentation have you read?
    validations:
      required: false
      
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of jellylogger are you using?
      options:
        - latest
        - 1.0.0
        - Other (please specify in context)
    validations:
      required: false
      
  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, please provide a minimal code sample that demonstrates your question.
      render: typescript
    validations:
      required: false
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm you've done the following
      options:
        - label: I've searched existing issues for similar questions
          required: true
        - label: I've read the documentation
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true
