blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/jellisy/jellylogger#readme
    about: Please check the documentation first
  - name: 💬 Discussions
    url: https://github.com/jellisy/jellylogger/discussions
    about: Ask questions and discuss ideas with the community